services:
  web_generator:
    build: ./generators
    command: python web_generator/traffic_generator.py
    environment:
      TRAFFIC_MODE: ${TRAFFIC_MODE}
    volumes:
      - ./data:/app/data
    networks:
      - soc-shared

  auth_generator:
    build: ./generators
    command: python authentication_generator/auth_generator.py
    environment:
      TRAFFIC_MODE: ${TRAFFIC_MODE}
    volumes:
      - ./data:/app/data
    networks:
      - soc-shared

  endpoint_generator:
    build: ./generators
    command: python endpoint_generator/generator.py
    environment:
      TRAFFIC_MODE: ${TRAFFIC_MODE}
    volumes:
      - ./data:/app/data
    networks:
      - soc-shared

  network_generator:
    build: ./generators
    command: python network_generator/network_generator.py
    environment:
      TRAFFIC_MODE: ${TRAFFIC_MODE}
    volumes:
      - ./data:/app/data
    networks:
      - soc-shared

  dashboard:
    build: ./dashboard
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      OPENSEARCH_URL: https://wazuh.indexer:9200
      OPENSEARCH_USER: admin
      OPENSEARCH_PASS: SecretPassword
    networks:
      - soc-shared

networks:
  soc-shared:
    external: true